version: '3.8'

services:
  client:
    build:
      context: ./client
    volumes:
      - ./client/logs:/app/logs
      - ./client:/app/client
      - "./client/Dataset Analysis:/app/Dataset Analysis"
    networks:
      - app-network
    depends_on:
      - server
    environment:
      - ANALYZE_DATASET=yes # Set to no to skip analysis on repeated benchmark runs
      - NUM_SAMPLES=1 # Adjust the number of samples as needed
      - NUM_FUZZING_ROUNDS=1 # Adjust the number of fuzzing rounds as needed

  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server/logs:/app/logs
      - ./server:/app/server
    networks:
      - app-network
    depends_on:
      - rb_waf
      - ml_waf

  rb_waf:
    build:
      context: ./rb_waf
    networks:
      - app-network

  ml_waf:
    build:
      context: ./ml_waf
    ports:
      - "8000:8000"  # Map ML service port 8000 to host port 8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
